spring:
  # null不传递给前端
  jackson:
    default-property-inclusion: non_null

  application:
    name: lzm-start
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lzmall?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  security:
    user:
      name: admin
      password: 123456

  netty:
    leak-detection: advanced

mybatis-plus:
  check-config-location: true
  mapper-locations:
    - classpath:mapper/*.xml # 扫描mapper包下的所有mapper文件
    - classpath*:com/**/mapper/*.xml # 扫描com包下的所有mapper文件
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl



# jwt配置
jwt:
  secret: s9iuhfoiu349857tue89rjhfoidshf5t
  access-expiration: 1800000 # 30分钟
  refresh-expiration: 604800000 # 7天
  header: Authorization
  prefix: Bearer

security:
  ignore:
    urls:
      - /user/login
      - /user/register
      - /admin/login
      - /admin/register
      - /swagger/**
      - /v3/api-docs/**
      - /*/*.html
      - /*/*.css
      - /*/*.js
      - /*/*.png
      - /favicon.ico
      - /test/checkLink
